# -*- coding: utf-8 -*-
"""Phonebook_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zihOfg6EP1vGTI55WG68tnDxwYuLqi3q
"""

import re 
regex = "^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$"
def check(email):  
    if(re.search(regex,email)):  
        return True
    else:  
        return False

def searchUser(name):
    filename="/content/data(1).txt"
    d={}
    with open(filename) as f:
        for line in f:
            userdetails=[]
            line=line.strip()
            alist=line.split(' ')
            userdetails=alist[1],alist[2]
            d[alist[0]]=userdetails
    user=d.get(name,"No contact with that name")
    if(len(user)==2):
        print("Name:",name)
        print("Email:",user[0])
        print("Phone:",user[1])
    else:
        print(user)
        addnew=input("Would you like to add the new user? Answer with Y or y to add")
        if(addnew=="Y" or addnew=="y"):  
          email=input("Please enter Email: \n ")          
          while (check(email)==False):
            print("Invalid email address format specified")
            email=input("Please enter Email:\n ")
          phone=input("Please enter Phone \n")
          f=open('/content/data(1).txt', "a+")
          f.write('%s %s %s\n'%(name,phone,email))
          f.close()
          print('%s Has been added to the text file successfully'%name)
           
name=input("Please enter name to search: ")
searchUser(name)